# Site settings
title: Jekyll Sunday
description: "A Jekyll starter"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://area44.github.io/jekyll-sunday" # the base hostname & protocol for your site (no trailing slash)
twitter_username: 
github_username: AREA44
google_analytics: 
exclude: [readme.md]

sass:
  #style: compressed

# Build settings
markdown: kramdown

# Compress HTML
compress_html:
  clippings: all
  comments: []
  endings: [p, li, td]
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
